"""empty message

Revision ID: 68df491602ba
Revises: 26960eea1369
Create Date: 2026-04-22 17:39:53.540997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68df491602ba'
down_revision = '26960eea1369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_firstname'), ['firstname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_firstname'))
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
