"""empty message

Revision ID: aac451b18d39
Revises: 561854a53aa4
Create Date: 2026-04-27 19:21:24.894826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac451b18d39'
down_revision = '561854a53aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
